---

# Creates datatable: d_v_a_extern_table
table:

- d_v_a_id: 101
  disease: measles
  vaccine: mcv1
  activity: routine
  
- d_v_a_id: 102
  disease: measles
  vaccine: mcv2
  activity: routine
  
- d_v_a_id: 103
  disease: measles
  vaccine: measles
  activity: campaign
  
- d_v_a_id: 104
  disease: polio
  vaccine: ipv
  activity: all
  
- d_v_a_id: 105
  disease: polio
  vaccine: opv
  activity: all
